# Generated by Django 4.0.2 on 2022-03-05 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('github_username', models.CharField(max_length=50)),
                ('projects_desc', models.TextField(max_length=4000)),
                ('prog_languages', models.CharField(max_length=150)),
                ('prog_experience', models.TextField(max_length=2000)),
                ('facebook', models.CharField(max_length=200)),
                ('discord', models.CharField(max_length=40)),
                ('interests', models.TextField(max_length=2000)),
                ('teams', models.CharField(choices=[], max_length=30)),
                ('facultate', models.CharField(choices=[], max_length=30)),
                ('find_out', models.TextField(max_length=500)),
                ('ticket_status', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
