# Generated by Django 4.0.2 on 2022-03-13 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('github_username', models.CharField(max_length=50)),
                ('projects_desc', models.TextField(max_length=4000)),
                ('prog_languages', models.CharField(max_length=150)),
                ('prog_experience', models.TextField(max_length=2000)),
                ('facebook', models.URLField()),
                ('discord', models.CharField(max_length=40)),
                ('interests', models.TextField(max_length=2000)),
                ('university', models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], max_length=30)),
                ('find_out', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('rejected', 'rejected'), ('waiting', 'waiting'), ('accepted', 'accepted')], default='waiting', max_length=20)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
