# Generated by Django 4.0.2 on 2022-03-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='teams',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.BooleanField(default=False),
        ),
    ]
